version: '3.7'

services:
  jmmaster:
    image: i_jmeter_master
    build: 
      dockerfile: master.Dockerfile
    container_name: jmeter-master
    ports:
      - 2222:22
    volumes:  
      - ./jmx/:/opt/
    networks:
      - jmeter_net
  jmslave:
    image: i_jmeter_slave
    build: 
      dockerfile: slave.Dockerfile
    container_name: jmeter-slave01
    networks:
      - jmeter_net
  jmslave2:
    image: i_jmeter_slave
    build: 
      dockerfile: slave.Dockerfile
    container_name: jmeter-slave02
    networks:
      - jmeter_net

networks:
  jmeter_net:
    name: jmeternet
    driver: bridge